config/routes.rb
Rails.application.routes.draw do


  devise_for :charities
  devise_for :users
  resources :users, only: [:show]

  root to: 'home#index'


  resources :products
  resources :categories
  resources :orders

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end

  #=============================== API =======================================

  namespace :api do
     resources :products
     resources :categories
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
    items = if hash["cart"] then
      hash["cart"]["items"].map do |item_data|
        CartItem.new item_data["product_id"], item_data["quantity"]
      end
    else
      []
    end
      new items
    end

  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find { |item| item.product_id == product_id }
    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def count
    @items.length
  end

  def serialize
    items = @items.map do |item|
      {
        "product_id" => item.product_id,
        "quantity" => item.quantity
      }
    end
    {
      "items" => items
    }
  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart

  def add
    @cart.add_item params[:id]
    session["cart"] = @cart.serialize
    product = Product.find params[:id]
    redirect_to :back, notice: "Added #{product.name} to cart."
  end

  def show
  end

  def checkout
    @order_form = OrderForm.new user: User.new
  end
end

app/views/carts/checkout.html.erb
<div class="container-checkout">
  <p class="text-title"> You are checking out the following: </p>
      <table class="table table-striped">
        <thead class="name-table">
          <tr>
            <td> Image </td>
            <td> Name </td>
            <td> Category</td>
            <td> Size </td>
            <td> Item Price </td>
          </tr>
        </thead>
        <tbody>
          <% @cart.items.each do |item| %>

          <tr>
            <td><img src="<%= item.product.image %>" width="50px"></td>
            <td><%= item.product.name.capitalize %></td>
            <td><%= item.product.category.name %></td>
            <td><%= item.product.size %></td>
            <td class="price-item"><%= number_to_currency item.total_price %></td>
            <% end %>
          </tr>
          <tr class="total-price total-price-checkout">
          <td class="name-table">Total Price</td>  <td class="price-item"><%= number_to_currency @cart.total_price %></td>
          </tr>
        </tbody>
      </table>
</div>


  <div class="details-user-form">
    <%= form_for @order_form, url: orders_path do |f|%>
      <% f.fields_for :user, @order_form.user do |u| %>
        <p class="text-title">Fill the form with your details</p>
        <p><%= render "orders/errors" %></p>
        <p><%= u.text_field :name, placeholder: "Name" %></p>
        <p><%= u.text_field :email, placeholder: "Email" %></p>
        <p><%= u.text_field :address, placeholder: "Address" %></p>
        <p><%= u.text_field :postal_code, placeholder: "Postal code" %></p>
        <p><%= u.text_field :city, placeholder: "City" %></p>
        <p><%= u.text_field :country, placeholder: "Country" %></p>
        <%= f.submit "Place order", class: "order-btn"%><br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/carts/show.html.erb
<div class="container-cart">

      <table class="table table-striped">
        <thead class="name-table">
          <tr>
            <td> Image </td>
            <td> Name </td>
            <td> Category</td>
            <td> Size </td>
            <td> Item Price </td>
          </tr>
        </thead>
        <tbody>
          <% @cart.items.each do |item| %>

          <tr>
            <td><img src="<%= item.product.image %>" width="50px"></td>
            <td><%= item.product.name.capitalize %></td>
            <td><%= item.product.category.name %></td>
            <td><%= item.product.size %></td>
            <td class="price-item"><%= number_to_currency item.total_price %></td>
            <% end %>
          </tr>
          <tr class="total-price">
          <td class="name-table">Total Price</td>  <td class="price-item"><%= number_to_currency @cart.total_price %></td>
          </tr>
        </tbody>
      </table>


    <button class="checkout-btn"><%= link_to 'Checkout', checkout_cart_path %></button>

</div>