config/routes.rb
Rails.application.routes.draw do


  devise_for :charities
  devise_for :users
  resources :users, only: [:show]

  root to: 'home#index'


  resources :products
  resources :categories
  resources :orders

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end

  #=============================== API =======================================

  namespace :api do
     resources :products
     resources :categories
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category

end

app/controllers/api/products_controller.rb
module Api
  class ProductsController < ApplicationController
    before_filter :initialize_cart
    before_action :authenticate_seller!, only: [:new, :edit, :update, :create, :destroy]

    def index
      @products= Product.all
      render json: @products.to_json, status: 201
    end

    def show
      @product = Product.find(params[:id])
      render json: @product.to_json, status: 201

    end

    def create
      product = Product.new
      product.name = params[:name]
      product.image = params[:image]
      product.size = params[:size]
      product.description = params[:description]
      product.price = params[:price]
      product.category_id = params[:category]
      product.user_id = current_user.id
      product.save
      render json: product.to_json, status: 201

    end

    def update
      @product = Product.find(params[:id])
      @product.name = params[:name]
      @product.image = params[:image]
      @product.size = params[:size]
      @product.description = params[:description]
      @product.price = params[:price]
      @product.category_id = params[:category]
      @product.user_id = current_user.id
      render json: @product.to_json, status: 201

    end

    def destroy
      product = Product.find(params[:id])
      product.destroy
      render json: product.to_json, status: 201

    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :initialize_cart
  before_action :authenticate_seller!, only: [:new, :edit, :update, :create, :destroy]


  def index
    @products = Product.all
  end

  def create
    product = Product.new
    product.name = params[:name]
    product.image = params[:image]
    product.size = params[:size]
    product.price = params[:price]
    product.description = params[:description]
    product.category_id = params[:category]
    product.user_id = current_user.id
    if product.save
      redirect_to "/products/#{ params[:id] }"
    else
      puts "error"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:name]
    @product.image = params[:image]
    @product.size = params[:size]
    @product.price = params[:price]
    @product.description = params[:description]
    @product.category_id = params[:category]
    @product.user_id = current_user.id
    @product.save

  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
  end

end

app/views/products/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @product %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h4 class="title-page"> All the products available </h4>

<% if user_signed_in? %>
<a href="#productsNew" class="btn btn-default btn-xl modal-trigger waves-effect waves-light btn link-to-new-item">
  Add new product!</a>
<% end %>

<section id="portfolio" class="bg-light-gray section-box-item">

  <% @products.each do |product| %>
    <div class="form-product-container" id="product<%= product.id%>" data-target="modal<%= product.id %>">
      <div class="col-md-4 col-sm-6 portfolio-item">
        <img src="<%= product.image %>" alt="" class="img-cards-item">
      </div>
      <div class="portfolio-caption name-item-cards">
        <a class="link-see-more modal-trigger" href="#productstab<%= product.id %>"> See more </a>
        <h6 class="name-product"><%= product.name.capitalize %></h6>
      </div>
    </div>
  <% end %>

</section>


  <% @products.each do |product| %>
    <div id="productstab<%= product.id %>" class="modal div-modal">
      <h5 class="name-modal"><%= product.name.capitalize %></h5>
      <div class="product-modal">
        <img class="img-modal" src="<%= product.image %>">
      </div>
      <div class="info-modal">
        <table class="table table-striped ">
          <tbody>
            <tr>
              <td class="name-table">Size </td>
              <td><%= product.size %></td>
            </tr>
            <tr>
              <td class="name-table"> Price </td>
              <td class="price-item"><%= number_to_currency  product.price %></td>
            </tr>
            <tr>
              <td class="name-table"> About </td>
              <td><%= product.description %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="modal-footer link-to-cart">
        <a rel="nofollow" data-method="post" href="/cart/add/<%= product.id %>">Add to cart</a>
      </div>
    </div>
  <% end %>


<!-- Modal Structure -->
<div id="productsNew" class="modal box-new-product">
  <div class="modal-content">
    <h4 class="title-new-product">Insert a new item to sell</h4>
    <div class="new-product-form">
      <form action="/products" method="post" enctype='multipart/form-data'>

        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label class="label-product">Name</label><br>
        <input type="text" name="name"><br>

        <label class="label-product">Size</label><br>
        <input type="text" name="size"><br>

        <label class="label-product">Image</label><br>
        <input type="file" name="image"><br>

        <div class="dropdown-category">
          <label class="label-product">Category</label><br>
          <select name="category" class="select-category">
            <% Category.all.each do |category| %>
              <option value="<%= category.id %>"> <%= category.name %></option>
            <% end %>
          </select>
        </div><br>

        <label class="label-product">Description</label><br>
        <textarea name="description"></textarea><br>

        <label class="label-product">Price</label><br>
        <input type="number" name="price" placeholder="  $"><br>

        <button class="btn-product-form modal-action modal-close waves-effect waves-green btn-flat product-new-btn"> Save </button><br>
      </form>
    </div>
  </div>

</div>



<script>
  $(document).ready(function(){
    $(".modal-trigger").leanModal();
  })
</script>

app/views/products/show.html.erb
<div class="box-single-item">
  <h2><%= @product.name %></h2>
  <p><%= @product.size %></p>
  <p><%= @product.description %></p>
  <p><%= number_to_currency @product.price %></p>
  <img src="<%= @product.image %>" width="150px" heigth="150px">

<button><%= link_to "Add to cart" , add_cart_path, method: :post %></button>


  <button><%= link_to 'Back', products_path %></button>
</div>