config/routes.rb
Rails.application.routes.draw do


  devise_for :charities
  devise_for :users
  resources :users, only: [:show]

  root to: 'home#index'


  resources :products
  resources :categories
  resources :orders

  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end

  #=============================== API =======================================

  namespace :api do
     resources :products
     resources :categories
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <title>BeforeYouGo</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://use.fontawesome.com/3ffabadf5d.js"></script>
        <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:700' rel='stylesheet' type='text/css'>
    </head>
    <body>

        <nav class="application-menu-bar navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand page-scroll" href="#page-top">Before you go</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="/" class="page-scroll">Home</a>
                        </li>


                        <% if user_signed_in? || charity_signed_in? %>

                          <% if user_signed_in? %>
                          <li>
                            <a href="/users/<%= current_user.id %>">
                              <i class="fa fa-user" aria-hidden="true">
                              </i>
                              Profile
                            </a>
                          </li>
                            <% if @cart %>
                              <% if @cart.empty? %>
                                <li>
                                  <i class="fa fa-shopping-cart fa-2x trolley" aria-hidden="true" style="font-size: 9px;"></i>
                                </li>
                              <% else %>
                                <li>
                                  <a href="/cart" class="page-scroll" style="font-size: 9px;">
                                    <i class="fa fa-shopping-cart fa-2x trolley" aria-hidden="true">
                                      <%= @cart.count %>
                                    </i>
                                  </a>
                                </li>

                              <% end %>
                            <% end %>
                        <li>
                            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                        </li>




                        <% elsif charity_signed_in? %>
                        <li>
                            <%= link_to "Logout", destroy_charity_session_path, method: :delete %>
                        </li>
                        <% end %>
                        <% elsif !user_signed_in? || !charity_signed_in?%>
                        <li>
                          <%= link_to "Login User", new_user_session_path %>
                        </li>

                        <li>
                          <%= link_to "Login Charity", new_charity_session_path %>
                        </li>
                      <% end %>


                    </ul>
                </div>
            </div>
        </nav>


        <div class="layout-stuff">
            <% if notice %>
            <div class="alert alert-success"><%= notice %></div>
            <% elsif alert %>
            <div class="alert alert-danger"><%= alert %></div>
            <% end %>
        </div>

        <%= yield %>

    </body>
</html>